#macro N_CHUNCKS_W 5
#macro N_CHUNCKS_H 5

#macro CHUNCK_WIDTH 8
#macro CHUNCK_HEIGHT 8
#macro CHUNCK_DEPTH 32

#macro N_TOTAL_BLOCKS_W N_CHUNCKS_W*CHUNCK_WIDTH
#macro N_TOTAL_CLOCKS_H N_CHUNCKS_H*CHUNCK_HEIGHT

#macro SELL_SIZE 32 